class AppLabels {
  static const Map<String, Map<String, String>> data = {
    "es": {
      "vibracion": "Vibración",
      "juegaen": "En",
      "canalizando": "Canalizando tu suerte...",
      "info_titulo": "Información Mística",
      "editar_nombre": "Nombre del sorteo",
      "buscar": "Buscar en favoritos...",
      "suerte_con": "¡Suerte con LuckyPass!",
      "apoyar_msj": "Próximamente: Canal de apoyo.",
      "juegos_de": "Juegos de:",
      "probabilidad": "Probabilidad de Éxito",
      "ganados": "¡PREMIADOS!",
      "marcar_ganador": "Marcar como ganador",
      "efectividad": "Efectividad",
      "tu_suerte_en": "Tu suerte está en:",
      "oraculo_titulo": "Oráculo de Resultados",
      "oraculo_hint": "Número ganador",
      "verificar": "VERIFICAR CONEXIÓN",
      "seleccionar_lotto": "Seleccionar sorteo",
      "tab_favs": "MIS NÚMEROS",
      "tab_historial": "HISTORIAL"
    },
    "en": {
      "vibracion": "Vibration",
      "juegaen": "In",
      "canalizando": "Channeling your luck...",
      "info_titulo": "Mystic Info",
      "editar_nombre": "Draw name",
      "buscar": "Search favorites...",
      "suerte_con": "Good luck with LuckyPass!",
      "apoyar_msj": "Coming soon: Support channel.",
      "juegos_de": "Games from:",
      "probabilidad": "Success Probability",
      "ganados": "WINNERS!",
      "marcar_ganador": "Mark as winner",
      "efectividad": "Effectiveness",
      "tu_suerte_en": "Your luck is in:",
      "oraculo_titulo": "Results Oracle",
      "oraculo_hint": "Winning number",
      "verificar": "CHECK CONNECTION",
      "seleccionar_lotto": "Select draw",
      "tab_favs": "MY NUMBERS",
      "tab_historial": "HISTORY"
    },
    "zh": {
      "vibracion": "能量振动",
      "juegaen": "建议投注",
      "canalizando": "正在感应你的财运...",
      "info_titulo": "神秘信息",
      "editar_nombre": "编辑名称",
      "buscar": "搜索收藏...",
      "suerte_con": "祝你好运 LuckyPass!",
      "apoyar_msj": "即将推出：支持渠道。",
      "juegos_de": "博彩游戏:",
      "probabilidad": "中奖概率",
      "ganados": "中奖号码!",
      "marcar_ganador": "设为中奖",
      "efectividad": "胜率",
      "tu_suerte_en": "你的财运 en:",
      "oraculo_titulo": "开奖先知",
      "oraculo_hint": "中奖号码",
      "verificar": "检查连接",
      "seleccionar_lotto": "选择博彩",
      "tab_favs": "我的号码",
      "tab_historial": "历史记录"
    }
  };
}